// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BookApp.Models
{
    public partial class Notes
    {
        public string Title { get; set; }
        public string Body { get; set; }
        public int Id { get; set; }
    }
}