// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BookApp.Models
{
    public partial class Tasks
    {
        public int Id { get; set; }
        public bool Done { get; set; }
        public string Taskname { get; set; }
        public DateTime? Time { get; set; }
    }
}